package spreadsheetGUI;

import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class SpreadsheetGUI extends javax.swing.JFrame implements ISpreadsheetWindow
{

    /**
     * Creates new form SpreadsheetGUI
     */
    public SpreadsheetGUI()
    {
        initComponents();
        
        // keep around a reference to a JFileChooser so location of selected 
        // files will stick around
        fileChooser = new JFileChooser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spreadsheetProgramDialog = new javax.swing.JDialog();
        dialogScrollPane = new javax.swing.JScrollPane();
        dialogLabel = new javax.swing.JLabel();
        dialogButtonPanel = new javax.swing.JPanel();
        dialogOkButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        currentCellLabel = new javax.swing.JLabel();
        currentCellTextField = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        contentsLabel = new javax.swing.JLabel();
        contentsTextField = new javax.swing.JTextField();
        contentsButton = new javax.swing.JButton();
        spreadsheetPanel = new spreadsheetGUI.SpreadsheetPanel();
        windowMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        howToUseMenuItem = new javax.swing.JMenuItem();

        spreadsheetProgramDialog.setMaximumSize(new java.awt.Dimension(450, 2147483647));

        dialogScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        dialogScrollPane.setAutoscrolls(true);
        dialogScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dialogScrollPane.setMaximumSize(new java.awt.Dimension(450, 32767));

        dialogLabel.setMaximumSize(new java.awt.Dimension(250, 0));
        dialogScrollPane.setViewportView(dialogLabel);

        spreadsheetProgramDialog.getContentPane().add(dialogScrollPane, java.awt.BorderLayout.CENTER);

        dialogOkButton.setText("Ok");
        dialogOkButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dialogOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogButtonPanelLayout = new javax.swing.GroupLayout(dialogButtonPanel);
        dialogButtonPanel.setLayout(dialogButtonPanelLayout);
        dialogButtonPanelLayout.setHorizontalGroup(
            dialogButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogButtonPanelLayout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(dialogOkButton)
                .addContainerGap())
        );
        dialogButtonPanelLayout.setVerticalGroup(
            dialogButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogOkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        spreadsheetProgramDialog.getContentPane().add(dialogButtonPanel, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        currentCellLabel.setText("Current Cell");

        currentCellTextField.setEditable(false);
        currentCellTextField.setColumns(5);

        valueLabel.setText("Value");

        valueTextField.setEditable(false);
        valueTextField.setColumns(15);

        contentsLabel.setText("Contents");

        contentsButton.setText("Enter Contents");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentCellLabel)
                    .addComponent(contentsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currentCellTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueTextField))
                    .addComponent(contentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentsButton)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCellLabel)
                    .addComponent(currentCellTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contentsLabel)
                    .addComponent(contentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contentsButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        spreadsheetPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(spreadsheetPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newMenuItem.setText("New");
        fileMenu.add(newMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        closeMenuItem.setText("Close");
        fileMenu.add(closeMenuItem);

        windowMenuBar.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        howToUseMenuItem.setText("How to use");
        helpMenu.add(howToUseMenuItem);

        windowMenuBar.add(helpMenu);

        setJMenuBar(windowMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogOkButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dialogOkButtonActionPerformed
    {//GEN-HEADEREND:event_dialogOkButtonActionPerformed
        spreadsheetProgramDialog.setVisible(false);
    }//GEN-LAST:event_dialogOkButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JButton contentsButton;
    private javax.swing.JLabel contentsLabel;
    private javax.swing.JTextField contentsTextField;
    private javax.swing.JLabel currentCellLabel;
    private javax.swing.JTextField currentCellTextField;
    private javax.swing.JPanel dialogButtonPanel;
    private javax.swing.JLabel dialogLabel;
    private javax.swing.JButton dialogOkButton;
    private javax.swing.JScrollPane dialogScrollPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem howToUseMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private spreadsheetGUI.SpreadsheetPanel spreadsheetPanel;
    private javax.swing.JDialog spreadsheetProgramDialog;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    private javax.swing.JMenuBar windowMenuBar;
    // End of variables declaration//GEN-END:variables

    private JFileChooser fileChooser;

    /**
     * Gets the spreadsheet panel component in this window
     */
    @Override
    public SpreadsheetPanel getSpreadsheetPanel()
    {
        return spreadsheetPanel;
    }

    /**
     * Sets the text of the current cell text box
     */
    @Override
    public void setCurrentCellText(String text)
    {
        currentCellTextField.setText(text);
    }

    /**
     * Sets the text of the value test box
     */
    @Override
    public void setValueBoxText(String text)
    {
        valueTextField.setText(text);
    }

    /**
     * Gets the text of the contents text box
     */
    @Override
    public String getContentsBoxText()
    {
        return contentsTextField.getText();
    }

    /**
     * Sets the text of the contents text box
     */
    @Override
    public void setContentsBoxText(String text)
    {
        contentsTextField.setText(text);
    }

    /**
     * Sets the text of this window
     */
    @Override
    public String getWindowText()
    {
        return getTitle();
    }

    /**
     * Sets the text of this window
     */
    @Override
    public void setWindowText(String text)
    {
        setTitle(text);
    }

    /**
     * Shows an error message box corresponding message
     */
    @Override
    public void showErrorMessageBox(String message)
    {
        JOptionPane.showMessageDialog(this, message,
                "Spreadsheet Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Shows a message box which can be canceled with a corresponding message
     * and caption
     */
    @Override
    public int showYesNoCancelMessageBox(String message, String caption)
    {
        return JOptionPane.showConfirmDialog(this, message, caption, 
                JOptionPane.YES_NO_CANCEL_OPTION);
    }
    
    /**
     * Shows a generic message box with the corresponding message and caption
     */
    @Override
    public void showOkayMessageBox(String message, String caption)
    {
        // avoid updating dialog while visible
        if (spreadsheetProgramDialog.isVisible())
        {
            spreadsheetProgramDialog.setVisible(false);
        }
        
        dialogLabel.setText(message);
        spreadsheetProgramDialog.setTitle(caption);
        spreadsheetProgramDialog.setSize(spreadsheetProgramDialog.getPreferredSize().width, 
                (int)(spreadsheetProgramDialog.getPreferredSize().width * 0.66));
        dialogScrollPane.getVerticalScrollBar().setValue(0);
        dialogScrollPane.getVerticalScrollBar().setUnitIncrement(10);
        spreadsheetProgramDialog.setLocationRelativeTo(this);
        spreadsheetProgramDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
        spreadsheetProgramDialog.setVisible(rootPaneCheckingEnabled);  
        
    }

    /**
     * Sets the cell in the SpreadsheetPanel located at row, col to the String
     * text
     */
    @Override
    public void setCellText(int row, int col, String text)
    {
        spreadsheetPanel.setValue(row, col, text);
    }

    /**
     * Gets the zero indexed row of the currently selected cell
     */
    @Override
    public int getCellSelectionRow()
    {
        return spreadsheetPanel.getSelectionRow();
    }

    /**
     * Gets the zero indexed column of the currently selected cell
     */
    @Override
    public int getCellSelectionColumn()
    {
        return spreadsheetPanel.getSelectionColumn();
    }

    /**
     * Closes this window
     */
    @Override
    public void closeWindow()
    {
        this.dispose();
        System.exit(0);
    }

    /**
     * Adds ActionListener l to the contents box
     */
    @Override
    public void addActionListenerToContentsBox(ActionListener l)
    {
        contentsTextField.addActionListener(l);
    }

    /**
     * Sets the focus to the contents text box
     */
    @Override
    public void setFocusToContentBox()
    {
        contentsTextField.requestFocus();
    }

    /**
     * Adds WindowListener l to the FormClosing event
     */
    @Override
    public void addFormClosingAction(WindowListener l)
    {
        this.addWindowListener(l);
    }

    /**
     * Sets the default cell as selection in the spreadsheet panel
     */
    @Override
    public void setCellSelectionToDefault()
    {
        spreadsheetPanel.setSelection(0, 0);
    }

    /**
     * Adds a listener to the enterContentsButton
     */
    @Override
    public void addActionListenerToEnterContentsButton(ActionListener l)
    {
        contentsButton.addActionListener(l);
    }

    /**
     * Shows an open file dialogue box and returns the file selection
     */
    @Override
    public String showOpenFileDialogue()
    {
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            return fileChooser.getSelectedFile().toString();
        } else
        {
            return "";
        }
    }

    /**
     * Shows an close file dialogue box and returns the file selection
     */
    @Override
    public String showSaveFileDialogue()
    {
        int returnVal = fileChooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            return fileChooser.getSelectedFile().toString();
        } else
        {
            return "";
        }
    }

    /**
     * Adds a listener to the Open menu item
     */
    @Override
    public void addActionListenerToOpenMenuItem(ActionListener l)
    {
        openMenuItem.addActionListener(l);
    }

    /**
     * Adds a listener to the Save menu item
     */
    @Override
    public void addActionListenerToSaveMenuItem(ActionListener l)
    {
        saveMenuItem.addActionListener(l);
    }

    /**
     * Adds a listener to the New menu item
     */
    @Override
    public void addActionListenerToNewMenuItem(ActionListener l)
    {
        newMenuItem.addActionListener(l);
    }
    
    /**
     * Adds a listener to the Close menu item l
     */
    @Override
    public void addActionListenerToCloseMenuItem(ActionListener l)
    {
        closeMenuItem.addActionListener(l);
    }
    
    /**
     * Adds a listener to the How To Use menu item l
     */
     @Override
    public void addActionListenerToHowToUseMenuItem(ActionListener l)
    {
        howToUseMenuItem.addActionListener(l);
    }

    /**
     * Adds a listener to the About menu item l
     */
    @Override
    public void addActionListenerToAboutMenuItem(ActionListener l)
    {
        aboutMenuItem.addActionListener(l);
    }

    /**
     * Returns the file chooser used by this window.
     *
     * Allows controller to control settings offered by file chooser
     */
    @Override
    public JFileChooser getFileChooser()
    {
        return fileChooser;
    }

}
